batch_size: 8
crop_size: 331
img_size: 354
model_name: PNASNet
path_model: models/PNASNet.pth.tar
transform: !!python/object:data_augmentation.DataTransform
  _num_crops: 10
  aug_rotate: 0
  aug_shear: 0
  crop_mode: ten
  flip_h: null
  no_bg: true
  normalize: true
  pad: true
  random_crop_factor: 0.08
  ten_crop_positions:
  - 0
  - 1
  - 8
target_mean: 0.5
target_std: 0.5