batch_size: 32
crop_size: 320
img_size: 366
model_name: DenseNet161
path_model: models/DenseNet161.pt
transform: !!python/object:data_augmentation.DataTransform
  _num_crops: 10
  aug_rotate: 0
  aug_shear: 0
  crop_mode: ten
  flip_h: null
  no_bg: true
  normalize: false
  pad: true
  random_crop_factor: 0.08
  ten_crop_positions:
  - 6
  - 3
  - 4
target_mean: 0.5
target_std: 0.5