train:
  batch_size: 20
  beta1: 0.8836082775250997
  beta2: 0.999
  epoch_num: 60
  is_nesterov: false
  learning_rate: 0.0001
  optimizer_name: adam
  transform: !!python/object:data_augmentation.DataTransform
    _num_crops: 0
    aug_rotate: 22.395857457210685
    aug_shear: 0
    crop_mode: random
    flip_h: random
    no_bg: true
    normalize: false
    pad: true
    random_crop_factor: 0.43137518532250163
    ten_crop_positions: null
  weight_decay: !!python/object/apply:numpy.core.multiarray.scalar
  - !!python/object/apply:numpy.dtype
    args:
    - f8
    - 0
    - 1
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    HKhvmRUC4j4=
valid:
  batch_size: 16
  crop_size: 320
  img_size: 366
  model_name: DenseNet201
  transform: !!python/object:data_augmentation.DataTransform
    _num_crops: 10
    aug_rotate: 0
    aug_shear: 0
    crop_mode: ten
    flip_h: null
    no_bg: true
    normalize: false
    pad: true
    random_crop_factor: 0.08
    ten_crop_positions: null
