train:
  batch_size: 20
  beta1: 0.9
  beta2: 0.999
  differential_lr: 10
  epoch_num: 60
  is_nesterov: false
  learning_rate: 3.548133892335755e-05
  optimizer_name: adam
  scheduling: Adaptive
  transform: !!python/object:data_augmentation.DataTransform
    _num_crops: 0
    aug_rotate: 23.428849915341154
    aug_shear: 13.858352739218823
    crop_mode: random
    flip_h: random
    no_bg: true
    normalize: false
    pad: true
    random_crop_factor: 0.09774943616251328
    ten_crop_positions: null
  weight_decay: 1.6696905692139798e-07
valid:
  batch_size: 16
  crop_size: 331
  img_size: 378
  model_name: InceptionV4
  transform: !!python/object:data_augmentation.DataTransform
    _num_crops: 10
    aug_rotate: 0
    aug_shear: 0
    crop_mode: ten
    flip_h: null
    no_bg: true
    normalize: false
    pad: true
    random_crop_factor: 0.08
    ten_crop_positions: null
