train:
  batch_size: 20
  beta1: 0.6383023594544934
  beta2: 0.999
  epoch_num: 60
  is_nesterov: false
  learning_rate: 0.0001
  optimizer_name: adam
  transform: !!python/object:data_augmentation.DataTransform
    _num_crops: 0
    aug_rotate: 27.35970666638483
    aug_shear: 0
    crop_mode: random
    flip_h: random
    no_bg: true
    normalize: false
    pad: true
    random_crop_factor: 0.09049768887771659
    ten_crop_positions: null
  weight_decay: 0.0
valid:
  batch_size: 16
  crop_size: 320
  img_size: 366
  model_name: DenseNet201
  transform: !!python/object:data_augmentation.DataTransform
    _num_crops: 10
    aug_rotate: 0
    aug_shear: 0
    crop_mode: ten
    flip_h: null
    no_bg: true
    normalize: false
    pad: true
    random_crop_factor: 0.08
    ten_crop_positions: null
