train:
  batch_size: 20
  beta1: 0.6352560719878773
  beta2: 0.999
  epoch_num: 60
  is_nesterov: false
  learning_rate: 3.0e-05
  optimizer_name: adam
  transform: !!python/object:data_augmentation.DataTransform
    _num_crops: 0
    aug_rotate: 27.11441725570169
    aug_shear: 0.35915152646117054
    crop_mode: random
    flip_h: random
    no_bg: true
    normalize: false
    pad: true
    random_crop_factor: 0.28046615220263515
    ten_crop_positions: null
  weight_decay: 1.8221858458900253e-05
valid:
  batch_size: 16
  crop_size: 224
  img_size: 256
  model_name: VGG16bn
  transform: !!python/object:data_augmentation.DataTransform
    _num_crops: 10
    aug_rotate: 0
    aug_shear: 0
    crop_mode: ten
    flip_h: null
    no_bg: true
    normalize: false
    pad: true
    random_crop_factor: 0.08
    ten_crop_positions: null
